x=[30 40 30 50 20 60]
y=[1 2 3 4 5 6]
subplot(3,1,1)
bar(x,y,'c')
xlabel('x-axis')
ylabel('y-axis')
xtitle('Bargrap 1')
xgrid()
subplot(3,1,2)
bar(x,y,'c')
xlabel('x-axis')
ylabel('y-axis')
xtitle('bargraph 2')
xgrid()
subplot(3,1,3)
bar(x,y,'c')
xlabel('x-axis')
ylabel('y-axis')
xtitle('bargraph 3')
xgrid()
